# Generated by Django 5.0.1 on 2025-03-12 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_book_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_image',
            new_name='image',
        ),
    ]
