# Generated by Django 5.0.1 on 2025-03-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='featured',
            field=models.CharField(choices=[('normal', 'normal'), ('popular', 'popular')], default='normal', max_length=25),
        ),
    ]
