# Generated by Django 5.0.1 on 2025-03-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_book_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='qoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qoute_of_day', models.CharField(blank=True, max_length=500, null=True)),
                ('qoute_author', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='featured',
            field=models.CharField(choices=[('normal', 'normal'), ('featured', 'featured'), ('popular', 'popular')], default='normal', max_length=25),
        ),
    ]
