# Generated by Django 5.0.1 on 2025-03-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_qoute_alter_book_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
